n1 = int(input('digite um numero para saber a tabuada: '))
print('1 x {} = '.format(n1), n1 * 1)
print('2 x {} = '.format(n1), n1 * 2)
print('3 x {} = '.format(n1), n1 * 3)
print('4 x {} = '.format(n1), n1 * 4)
print('5 x {} = '.format(n1), n1 * 5)
